version: 2.0

jobs:
  test:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run: ./mvnw test

  build:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run: ./mvnw -Dmaven.test.skip=true -Dmaven.javadoc.skip=true package

  analyse:
    docker:
      - image: circleci/openjdk:stretch
    steps:
      - checkout
      - run:
          name: Analyze on SonarCloud
          command: ./mvnw verify sonar:sonar

workflows:
  version: 2

  build-then-test:
    jobs:
      - build
      - test:
          requires:
            - build
      - analyse
          context: SonarCloud
