version: 2.1

orbs:
  maven: circleci/maven@1.1

workflows:
  version: 2
  build:
    jobs:
      - build
      - test
  jobs:
    build:
      steps:
        - checkout
        - run: mvn clean compile
    test:
      steps:
        - checkout
        - run: mvn test
