version: 2.1

orbs:
  maven: circleci/maven@0.0.12

workflows:
  version: 2
  build:
    jobs:
      - build


jobs:
  build:
    steps:
      - checkout
      - run:
          name: build
          command: mvn compile

